### ISSUE TITLE
How to get test results and evaluation metrics

### ISSUE THREAD

**Issue by EMCL** [yugaljain1999/Video_Captioning_Pytorch#3]
hi,
can you please implement evaluation metrics like BLUE etc and test a single video.

**Comment by yugaljain1999** [comment]
I will implement evaluation part soon.. 
Stay tuned..

**Comment by yugaljain1999** [comment]
@EMCL I am implementing evaluation part and it will publish in 3-4 days.. If you have already trained model , can you share weights here?
